name: Format PHP Code

on:
  push:
    branches: [ main ]
    paths:
      - '**.php'
      - '.github/workflows/php-cs-fixer.yml'
  pull_request:
    types: [ opened, synchronize ]
  workflow_call:

jobs:
  format-code:
    name: P${{ matrix.php }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: ['7.4','8.4','8.5']

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install composer dependencies
        uses: ramsey/composer-install@v4

      - name: Run PHP CS Fixer
        run: composer format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Fix styling
